name: Java CI with Gradle

on:
  release:
    types: [published]

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
    - name: Build with Gradle
      run: ./gradlew clean build
