name: Java CI with Gradle
run-name: Push release to the ghcr.io
on: [push]
  # release:
  #   types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    env:
      GH_USER: ${{ vars.GH_USER }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Login to the container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ vars.GH_USER }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Build and push
      run: |
        VERSION = $(echo "${GITHUB_REF}" | cut -d "/" -f3)
        docker build -t ghcr.io/present-is-a-gift/pomaranch-service:${VERSION} .
        docker push ghcr.io/present-is-a-gift/pomaranch-service:${VERSION}
