name: Java CI with Gradle
run-name: Push release to the ghcr.io
on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    env:
      NEW_VERSION: $(echo "${GITHUB_REF}" | cut -d "/" -f3)
    steps:
    - name: Checkout the code
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Login to the container registry
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ vars.GH_USER }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Build and push
    - uses: docker/build-push-action@v5
      run: echo $NEW_VERSION
      with:
        push: true
        tags: present-is-a-gift/pomaranch-service:NEW_VERSION
