name: Java CI with Gradle
run-name: Publish release
on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    env:
      GH_USER: ${{ vars.GH_USER }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Login to the Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push release to the Docker Hub
      run: |
        NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
        echo "New version ${NEW_VERSION}"
        docker build -t erneman/pomaranch-service .
        docker tag erneman/pomaranch-service erneman/pomaranch-service:${NEW_VERSION}
        docker push -a erneman/pomaranch-service
